["protostar.config"]
protostar_version = "0.2.3"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
proposals = [
    "./contracts/Proposals.cairo",
]
artifacts = [
    "./contracts/Artifacts.cairo",
]
vrf = [
    "./contracts/vrf/pseudo-random.cairo",
]